### ISSUE TITLE
[Docs]: Disabling hash router breaks the build

### ISSUE THREAD

**Issue by TomFern** [semaphoreci/semaphore#210]
### Type

Bug report

### What do you want to report?

Running `npm run build` with the hash router disabled (default setting) causes the build to break.

```
[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/Users/tom/r/semaphore/docs/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
    at async /Users/tom/r/semaphore/docs/node_modules/@docusaurus/core/lib/commands/build.js:65:9
    at async mapAsyncSequential (/Users/tom/r/semaphore/docs/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
    at async Command.build (/Users/tom/r/semaphore/docs/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
  [cause]: Error: Docusaurus found broken links!
  
  Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
  Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
  
  It looks like some of the broken links we found appear in many pages of your site.
  Maybe those broken links appear on all pages through your site layout?
  We recommend that you check your theme configuration for such links (particularly, theme navbar and footer).
  Frequent broken links are linking to:
  - /docs/category/getting-started
  
  Exhaustive list of all broken links found:
  - Broken link on source page path = /404.html:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /category/api-specification:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /category/getting-started:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /category/reference:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /category/using-semaphore:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/about-semaphore:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/changelog:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/experiments:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/faq:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/guided-tour:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/migration/bitbucket:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/migration/circleci:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/migration/github-actions:
     -> linking to ./circle (resolved as: /getting-started/migration/circle)
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/migration/jenkins:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/migration/overview:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/migration/travis:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/tour/continuous-delivery:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/tour/continuous-integration:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/tour/hello-world:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /getting-started/tour/sign-up:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/dashboards-create:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/dashboards-delete:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/dashboards-describe:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/dashboards-list:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/dashboards-update:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/deployment-targets-activate:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/deployment-targets-create:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/deployment-targets-deactivate:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/deployment-targets-delete:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/deployment-targets-describe:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/deployment-targets-history:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/deployment-targets-list:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/deployment-targets-update:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/notifications-create:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/notifications-delete:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/notifications-describe:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/notifications-list:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/notifications-update:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/pipelines-describe:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/pipelines-describe-topology:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/pipelines-list:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/pipelines-partial-rebuild:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/pipelines-terminate:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/pipelines-validate-yaml:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/project-secrets-create:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/project-secrets-delete:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/project-secrets-describe:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/project-secrets-list:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/project-secrets-update:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/projects-create:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/projects-delete:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/projects-describe:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/projects-list:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/projects-update:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/secrets-create:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/secrets-delete:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/secrets-describe:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/secrets-list:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/secrets-update:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/self-hosted-agent-types-create:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/self-hosted-agent-types-delete:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/self-hosted-agent-types-describe:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/self-hosted-agent-types-disable-all:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/self-hosted-agent-types-list:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/self-hosted-agent-types-update:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/self-hosted-agents-describe:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/self-hosted-agents-list:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/semaphore-public-api:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/tasks-create:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/tasks-delete:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/tasks-describe:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/tasks-list:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/tasks-replace:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/tasks-trigger:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/tasks-update:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/workflows-describe:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/workflows-list:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/workflows-reschedule:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/workflows-schedule:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /openapi-spec/workflows-terminate:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/agent-yaml:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/api:
     -> linking to /essentials/parameterized-promotions/#setting-the-values-via-the-api
     -> linking to /reference/sem-command-line-tool/#sem-logs
     -> linking to /reference/artifact-retention-policies
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/audit-events:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/conditions-dsl:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/dashboard-yaml:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/deployment-target-yaml:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/env-vars:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/jobs-yaml:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/machine-types:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/notifications-yaml:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/openid:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/os-apple:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/os-ubuntu:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/pipeline-yaml:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/project-yaml:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/resources-yaml:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/secret-yaml:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/self-hosted-config:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/semaphore-cli:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /reference/toolbox:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/artifacts:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/connect-bitbucket:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/connect-github:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/connect-github-oauth:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/github-sso:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/insights:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/jobs:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/android:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/c-cpp:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/clojure:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/databases:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/elixir-erlang:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/go:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/java:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/javascript:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/php:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/python:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/ruby:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/rust:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/scala:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/languages/swift:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/monorepo:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/notifications:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/observability:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/okta:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/openid:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/optimization:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/optimization/cache:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/optimization/container-registry:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/optimization/docker:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/org-health:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/org-preflight:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/organizations:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/pipelines:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/projects:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/promotions:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/rbac:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/secrets:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/self-hosted:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/self-hosted-aws:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/self-hosted-configure:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/self-hosted-install:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/tasks:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/tests/flaky-tests:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/tests/test-reports:
     -> linking to /docs/category/getting-started
  - Broken link on source page path = /using-semaphore/workflows:
     -> linking to /docs/category/getting-started
  
      at throwError (/Users/tom/r/semaphore/docs/node_modules/@docusaurus/logger/lib/index.js:79:11)
      at reportBrokenLinks (/Users/tom/r/semaphore/docs/node_modules/@docusaurus/core/lib/server/brokenLinks.js:250:47)
      at handleBrokenLinks (/Users/tom/r/semaphore/docs/node_modules/@docusaurus/core/lib/server/brokenLinks.js:282:5)
      at executeBrokenLinksCheck (/Users/tom/r/semaphore/docs/node_modules/@docusaurus/core/lib/commands/build.js:200:47)
      at /Users/tom/r/semaphore/docs/node_modules/@docusaurus/core/lib/commands/build.js:146:66
      at Object.async (/Users/tom/r/semaphore/docs/node_modules/@docusaurus/core/lib/utils.js:36:47)
      at buildLocale (/Users/tom/r/semaphore/docs/node_modules/@docusaurus/core/lib/commands/build.js:146:30)
      at async tryToBuildLocale (/Users/tom/r/semaphore/docs/node_modules/@docusaurus/core/lib/commands/build.js:47:13)
      at async /Users/tom/r/semaphore/docs/node_modules/@docusaurus/core/lib/commands/build.js:65:9
      at async mapAsyncSequential (/Users/tom/r/semaphore/docs/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
      at async Command.build (/Users/tom/r/semaphore/docs/node_modules/@docusaurus/core/lib/commands/build.js:63:5)
}
[INFO] Docusaurus version: 3.4.0
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Fixed on #218. The main problem was a broken links in the footer.
